### ISSUE TITLE
PQ Capabilities ini to include local dimming level

### ISSUE THREAD

**Issue by ashishkumarrai1998** [rdkcentral/rdkv-halif-tvsettings#25]
This issue is to move new changes in pq_capabilites.ini

1. Added LocalDimmingLevel param.
2. Added new pq mode Graphics
3. Added new video source ALL in video source section
4. Added new CT's for WB (BoostStandard,BoostWarm,BoostCold,BoostUser,Supercold,BoostSupercold)

**Comment by akhilbhas** [comment]
Support for all the parameters mentioned in the description are already included in the Sink Profile YAML. 

https://github.com/rdkcentral/rdkv-halif-test-tvsettings/blob/main/profiles/sink/Sink_4K_TvSettings.yaml

**Comment by srinivasgtl** [comment]
@ashishkumarrai1998 , please look into this and see if it meets all the requirements as mentioned in this issue.  if it meets all the requirements, we can close the issue.

**Comment by hari22yuva** [comment]
merged to develop
