### ISSUE TITLE
Add support for DolbyMode Game

### ISSUE THREAD

**Issue by aktamilbe** [rdkcentral/rdkv-halif-tvsettings#27]
Add Game mode support in existing Dolbymode Enum.

**Comment by srinivasgtl** [comment]
Do we need L1 and L2 for this change?  I think the existing test cases should be able to cover this as they are added as part of the existing structure.

**Comment by aktamilbe** [comment]
> Do we need L1 and L2 for this change? I think the existing test cases should be able to cover this as they are added as part of the existing structure.

This changes only required only for one platform(Products specific changes.).

**Comment by hari22yuva** [comment]
merged to develop
