### ISSUE TITLE
Remove ODM specific apis from tvsettings HAL to make it generic - Phase 1

### ISSUE THREAD

**Issue by arjunbinu** [rdkcentral/rdkv-halif-tvsettings#46]
### Main Objective
The current activity focuses on removing soon-to-be deprecated ODM APIs and types from the TvSettings HAL headers, particularly those exposed to plugins and factory code.

### APIs Removed

**From include/tvSettings.h:**
_tvError_t GetTVSupportedHDR10Modes(tvDolbyMode_t *HDR10Modes[], unsigned short *count)
tvError_t GetTVSupportedHLGModes(tvDolbyMode_t *HLGModes[], unsigned short *count)_
Replaced by a common API: GetTVSupportedDolbyVisionModes to retrieve supported modes for DolbyVision, HDR10, and HLG.
 

**From include/tvSettingsExtODM.h:**
int ReadCapabilitiesFromConfODM(...)
Defintion moved to the plugin.

**From include/tvSettingsODM.h:**
_tvError_t GetSupportedVideoFormatsODM(unsigned int *videoFormats, unsigned short *numberOfFormats)_
_tvVideoHDRFormat_t GetCurrentVideoFormatODM(void)
tvError_t GetTVSupportedDimmingModesODM(char **dimmingModes, unsigned short *numDimmingModes)_
Stubbed replacements are now present in tvSettings.h.
Conversion APIs like _ConvertVideoFormatToHDRFormatODM_ and _ConvertHDRFormatToContentFormatODM_
Removed due to the deprecation of types like tvhdr_type_t and tvVideoHDRFormat_t.
_int GetPanelIDODM(char *panelid)_
Moved definition to the plugin. Further updates will encapsulate Panel ID retrieval in Phase 2.
_tvError_t TvSyncCalibrationInfoODM()_
Removed as the calibration data will now be handled differently.
_tvError_t GetTVSupportedDolbyVisionModesODM(pic_modes_t *dvModes[],unsigned short *count)_
Replaced by GetTVSupportedDolbyVisionModes in tvSettings.h.

Note:
Additional function removals are included in preparation for Phase 2.
 

### Modified APIs
**In include/tvSettings.h:**
tvError_t GetCurrentVideoSource(int *currentSource)
Updated to: tvError_t GetCurrentVideoSource(tvVideoSrcType_t *currentSource)
Rationale: To align with the expected type, ensuring consistency in API usage.
 

These changes are foundational for the overall API clean-up and ensure the TvSettings HAL interfaces are maintainable, and aligned with the upcoming architectural requirements.

**Comment by hari22yuva** [comment]
merged to develop
